server:
  port: ${PORT_NUM}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
jwt:
  secret: ${JWT_SECRET}

redirect_url: ${REDIRECT_URL}

spring:
  profiles:
    include:
      - oauth
      - db
      - mail
      - aws
      - log

